=== yuliia-zinchenko/OOP-3rd-year/lab_2/src/main/resources/lab/candies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.com/candies"
           xmlns:tns="http://www.example.com/candies"
           elementFormDefault="qualified">

    <xs:element name="Candies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Candy" type="tns:Candy" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Candy">
        <xs:sequence>
            <xs:element name="Name" type="tns:NameType"/>
            <xs:element name="Energy" type="tns:EnergyType"/>
            <xs:element name="Type" type="tns:CandyType"/>
            <xs:element name="Ingredients" type="tns:IngredientsType"/>
            <xs:element name="Value" type="tns:ValueType"/>
        </xs:sequence>

        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="production" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:simpleType name="NameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9\s\-]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="EnergyType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="100"/>
            <xs:maxInclusive value="1000"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CandyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Caramel"/>
            <xs:enumeration value="Toffee"/>
            <xs:enumeration value="Chocolate"/>
            <xs:enumeration value="ChocolateWithFilling"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="IngredientsType">
        <xs:sequence>
            <xs:element name="Water" type="tns:PositiveInt"/>
            <xs:element name="Sugar" type="tns:PositiveInt"/>
            <xs:element name="Fructose" type="tns:PositiveInt"/>
            <xs:element name="ChocolateType" type="tns:ChocolateType" minOccurs="0"/>
            <xs:element name="Vanillin" type="tns:PositiveInt"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="ChocolateType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Dark"/>
            <xs:enumeration value="Milk"/>
            <xs:enumeration value="White"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="ValueType">
        <xs:sequence>
            <xs:element name="Proteins" type="tns:PositiveInt"/>
            <xs:element name="Fats" type="tns:PositiveInt"/>
            <xs:element name="Carbohydrates" type="tns:PositiveInt"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="PositiveInt">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== yuliia-zinchenko/OOP-3rd-year/lab_2/target/test-classes/lab/test_candies.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:Candies xmlns:c="http://www.example.com/candies"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.example.com/candies ../../main/resources/lab/candies.xsd">

    <c:Candy id="t1" production="TEST_FACTORY_A">
        <c:Name>Test Toffee</c:Name>
        <c:Energy>400</c:Energy>
        <c:Type>Toffee</c:Type>
        <c:Ingredients>
            <c:Water>100</c:Water>
            <c:Sugar>1000</c:Sugar>
            <c:Fructose>100</c:Fructose>
            <c:Vanillin>10</c:Vanillin>
        </c:Ingredients>
        <c:Value>
            <c:Proteins>1</c:Proteins>
            <c:Fats>10</c:Fats>
            <c:Carbohydrates>80</c:Carbohydrates>
        </c:Value>
    </c:Candy>

    <c:Candy id="t2" production="TEST_FACTORY_B">
        <c:Name>Test Chocolate</c:Name>
        <c:Energy>600</c:Energy>
        <c:Type>ChocolateWithFilling</c:Type>
        <c:Ingredients>
            <c:Water>50</c:Water>
            <c:Sugar>500</c:Sugar>
            <c:Fructose>50</c:Fructose>
            <c:ChocolateType>Dark</c:ChocolateType>
            <c:Vanillin>20</c:Vanillin>
        </c:Ingredients>
        <c:Value>
            <c:Proteins>5</c:Proteins>
            <c:Fats>40</c:Fats>
            <c:Carbohydrates>55</c:Carbohydrates>
        </c:Value>
    </c:Candy>

</c:Candies>

=== yuliia-zinchenko/OOP-3rd-year/lab_2/target/classes/lab/candies.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:Candies xmlns:c="http://www.example.com/candies"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.example.com/candies candies.xsd">

    <c:Candy id="id1" production="Roshen">
        <c:Name>Red Poppy</c:Name>
        <c:Energy>550</c:Energy>
        <c:Type>ChocolateWithFilling</c:Type>
        <c:Ingredients>
            <c:Water>50</c:Water>
            <c:Sugar>300</c:Sugar>
            <c:Fructose>50</c:Fructose>
            <c:ChocolateType>Dark</c:ChocolateType>
            <c:Vanillin>10</c:Vanillin>
        </c:Ingredients>
        <c:Value>
            <c:Proteins>5</c:Proteins>
            <c:Fats>30</c:Fats>
            <c:Carbohydrates>60</c:Carbohydrates>
        </c:Value>
    </c:Candy>

    <c:Candy id="id2" production="Svitoch">
        <c:Name>Korivka</c:Name>
        <c:Energy>400</c:Energy>
        <c:Type>Toffee</c:Type>
        <c:Ingredients>
            <c:Water>100</c:Water>
            <c:Sugar>400</c:Sugar>
            <c:Fructose>0</c:Fructose>
            <c:Vanillin>20</c:Vanillin>
        </c:Ingredients>
        <c:Value>
            <c:Proteins>2</c:Proteins>
            <c:Fats>15</c:Fats>
            <c:Carbohydrates>70</c:Carbohydrates>
        </c:Value>
    </c:Candy>
    
    <c:Candy id="id3" production="AVK">
        <c:Name>Caramel Drops</c:Name>
        <c:Energy>380</c:Energy>
        <c:Type>Caramel</c:Type>
        <c:Ingredients>
            <c:Water>150</c:Water>
            <c:Sugar>500</c:Sugar>
            <c:Fructose>100</c:Fructose>
            <c:Vanillin>5</c:Vanillin>
        </c:Ingredients>
        <c:Value>
            <c:Proteins>0</c:Proteins>
            <c:Fats>10</c:Fats>
            <c:Carbohydrates>80</c:Carbohydrates>
        </c:Value>
    </c:Candy>

</c:Candies>
